// Copyright 2023 Kuznetsov Artem
#ifndef TASKS_TASK_2_KUZNETSOV_A_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_
#define TASKS_TASK_2_KUZNETSOV_A_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_

#include <mpi.h>

int sum(int a, int b);

#endif  // TASKS_TASK_2_KUZNETSOV_A_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_
